name: Update Quote

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update timestamp
        run: echo "Last updated: $(date)" > last_update.txt
      - name: Commit and push
        run: |
          git config --global user.name 'Amit barua'
          git config --global user.email 'amit.himel@example.com'
          git add last_update.txt
          git commit -m "Update timestamp"
          git push
